server {
    listen 80;
    server_name steered.dev www.steered.dev analytics.steered.dev abrex.app www.abrex.app;

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name steered.dev www.steered.dev;

    ssl_certificate /etc/letsencrypt/live/steered.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/steered.dev/privkey.pem;

    location = /google6ab6583e2acf7217.html {
        default_type text/html;
        return 200 "google-site-verification: google6ab6583e2acf7217.html";
    }

    location / {
        proxy_pass http://app:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name analytics.steered.dev;

    ssl_certificate /etc/letsencrypt/live/analytics.steered.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/analytics.steered.dev/privkey.pem;

    location / {
        proxy_pass http://analytics:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name firemark.steered.dev;

    ssl_certificate /etc/letsencrypt/live/firemark.steered.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/firemark.steered.dev/privkey.pem;

    location / {
        proxy_pass http://firemark_bot:8787;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 443 ssl;
    server_name abrex.app www.abrex.app;

    ssl_certificate /etc/letsencrypt/live/abrex.app/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/abrex.app/privkey.pem;

    location / {
        proxy_pass http://abrex:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}